### ISSUE TITLE
Kanban board: Recipe App (RoR Group Project)

### ISSUE THREAD

**Issue by katarighe** [katarighe/recipe-app#21]
Hello **Code Reviewer**,

For the RoR Group Project (Recipe App):

- Visit the GitHub project here: [GitHub Project](https://github.com/users/katarighe/projects/3/views/1).

- We are a team of 3 developers.

- Our team members are: 
  - @katarighe (User / Recipe)
  - @Errytagedesign (Recipe / Recipe Food)
  - @Abdulwhbhussain (Inventory / Inventory Food)

**Comment by DammyShittu** [comment]
Hi @katarighe, @Errytagedesign and @Abdulwhbhussain,

## APPROVED 🟢

## Highlights
✔️ Assigned tasks

Great implementation of all the requirements in this milestone. 👏 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

Congratulations! 🎉 

## CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
